[package]
name = "runes-for-mempool"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
serde = { version = "1.0.137", features = ["derive"] }
serde_with = "3.7.0"
serde_json = "1.0.116"
derive_more = "0.99.17"
hex = "0.4.3"